<a href="https://colab.research.google.com/github/AmitHasanShuvo/Neural-Network-Implementations/blob/master/Fashion_MINST_with_tf.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Todo : https://www.tensorflow.org/tutorials/keras/classification

In [0]:
import tensorflow as tf
import numpy as np


In [0]:
mnist = tf.keras.datasets.fashion_mnist

In [0]:
(training_images, training_labels),(test_images, test_labels) = mnist.load_data()

In [17]:
print(training_images[44])
print(training_labels[44])

[[  0   0   0   0   0   0   0   0   0   0   0   1   0  34 116   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0 201 254 247 255 255 255 255 255 255 255 255 142   0   1   0]
 [  0   0   0   0   0   0   0   0   0   0   2   0  68 227 224 238 249 244 247 245 244 244 243 255 218   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0 207 227 225 237 240 237 240 243 240 241 236 244 223   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0 177 234 235 235 241 240 243 246 244 244 244 239 255  18   0   1]
 [  0   0   0   0   0   0   0   0   0   1   0   0 220 216 236 237 245 242 241 244 244 243 248 228 255  91   0   0]
 [  0   0   0   0   0   0   0   0   0   1   0  17 255 242 239 232 236 239 239 243 243 243 244 231 255 215   0   0]
 [  0   0   0   0   0   0   0   0   0   1   0  53 245 217 236 231 234 239 240 240 241 243 242 239 236 255  68   0]
 [  0   0   0   0   0   0   0   0   0   0   0 130 255 226 233 233 235 240 243 24

In [0]:
training_images = training_images/255.0
test_images = test_images/255.0

In [0]:
model = tf.keras.models.Sequential([tf.keras.layers.Flatten(), #Flatten just takes that square and turns it into a 1 dimensional set.
                                    tf.keras.layers.Dense(128, activation=tf.nn.relu), 
                                    tf.keras.layers.Dense(256, activation=tf.nn.relu),

                                    #Dense : Adds a layer of neurons 
                                    #Relu effectively means "If X>0 return X, else return 0" -- so what it does
                                    #it it only passes values 0 or greater to the next layer in the network.
                                    tf.keras.layers.Dense(10, activation=tf.nn.softmax )]
                                   #Softmax takes a set of values, and effectively picks the biggest one, so, for example,
                                   #if the output of the last layer looks like [0.1, 0.1, 0.05, 0.1, 9.5, 0.1, 0.05, 0.05, 0.05],
                                   #it saves you from fishing through it looking for the biggest value, and turns it into [0,0,0,0,1,0,0,0,0] 
                                   #-- The goal is to save a lot of coding!
    
)

In [0]:
model.compile(optimizer=tf.optimizers.Adam(),
              loss = 'sparse_categorical_crossentropy',
              metrics = ['accuracy'])


In [30]:
model.fit(training_images,training_labels, epochs=10)

Epoch 1/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.4790 - accuracy: 0.8270
Epoch 2/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.3601 - accuracy: 0.8683
Epoch 3/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3245 - accuracy: 0.8808
Epoch 4/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3043 - accuracy: 0.8868
Epoch 5/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2843 - accuracy: 0.8926
Epoch 6/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2696 - accuracy: 0.8993
Epoch 7/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2563 - accuracy: 0.9039
Epoch 8/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2453 - accuracy: 0.9079
Epoch 9/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2352 - accuracy: 0.9107
Epoch 10/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.226

In [31]:
model.evaluate(test_images, test_labels)

313/313 [==============================] - 0s 1ms/step - loss: 0.3487 - accuracy: 0.8792


[0.3487033545970917, 0.8791999816894531]

In [27]:
classifications = model.predict(test_images)

print(classifications[0])

[4.11499798e-07 9.83806481e-10 2.15161240e-08 2.53048942e-08 1.09192366e-09 3.44441418e-04 1.04240094e-07 5.35346428e-03 7.63111174e-08 9.94301438e-01]


In [26]:
print(test_labels[0])

9


Callbacks


In [0]:
class myCallback(tf.keras.callbacks.Callback):
  def on_epoch_end(self, epoch, logs={}):
    if(logs.get('loss')<0.1):
      print("\nReached 90% accuracy so cancelling training!")
      self.model.stop_training = True
callbacks = myCallback()


                     

In [37]:
model.fit(training_images, training_labels, epochs=15, callbacks=[callbacks])


Epoch 1/15
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2118 - accuracy: 0.9192
Epoch 2/15
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2005 - accuracy: 0.9234
Epoch 3/15
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1944 - accuracy: 0.9246
Epoch 4/15
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1889 - accuracy: 0.9281
Epoch 5/15
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1824 - accuracy: 0.9300
Epoch 6/15
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1731 - accuracy: 0.9333
Epoch 7/15
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1737 - accuracy: 0.9335
Epoch 8/15
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1665 - accuracy: 0.9363
Epoch 9/15
1875/1875 [==============================] - 5s 2ms/step - loss: 0.1615 - accuracy: 0.9376
Epoch 10/15
1875/1875 [==============================] - 4s 2ms/step - loss: 0.156

Reference: https://github.com/lmoroney/dlaicourse/blob/master/Course%201%20-%20Part%204%20-%20Lesson%204%20-%20Notebook.ipynb
